### ISSUE TITLE
Fora do padrão da língua escolhida (pt-br)

### ISSUE THREAD

**Issue by rafamancan** [YarusskiDev/ProjetoLaravel#1]
https://github.com/YarusskiDev/ProjetoLaravel/blob/ac2209a9eb6863346a7f9d247b8be92a53a2f303/projetoCinema/app/Http/Controllers/UsuarioLoginController.php#L30-L53

Não vejo problema em uma tarefa usar o Português pra facilitar pra vc, porém vc tem que manter um padrão a partir do momento que escolhe se vai fazer em Portugues ou Ingles.

function LOGAR (pt-br) 
$credentials (en-us)

É um dos motivos que sempre optamos por escrever em Inglês os códigos, pra dar uma noção geral do contexto que está sendo escrito.

**Comment by YarusskiDev** [comment]
fixed
