### ISSUE TITLE
Validação de login

### ISSUE THREAD

**Issue by rafamancan** [YarusskiDev/ProjetoLaravel#13]
https://github.com/YarusskiDev/ProjetoLaravel/blob/ac2209a9eb6863346a7f9d247b8be92a53a2f303/projetoCinema/app/Services/UsuarioLoginService.php#L31-L42

Aqui no caso é uma questão de segurança.
Você abre a possibilidade de brute force pra descobrir usuário e e-mail.
O ideal era vc fazer a validação de e-mail/senha ao mesmo tempo

**Comment by YarusskiDev** [comment]
tb mudei.
