### ISSUE TITLE
Listando errado

### ISSUE THREAD

**Issue by rafamancan** [YarusskiDev/ProjetoLaravel#15]
https://github.com/YarusskiDev/ProjetoLaravel/blob/ac2209a9eb6863346a7f9d247b8be92a53a2f303/projetoCinema/resources/views/principal.blade.php#L1-L26

Está usando o mesmo array para exibir os filmes que estão sendo exibidos e os próximos 10, de alguma forma tinha que ter separado

**Comment by YarusskiDev** [comment]
mudei, da um bizu!
