### ISSUE TITLE
Criar novo usuário?

### ISSUE THREAD

**Issue by rafamancan** [YarusskiDev/ProjetoLaravel#2]
Nas espcificações do projeto não tinha o item para cadastrar usuário. Sendo que foi entregue 70% da tarefa, pq fazer algo a mais sem ter pedido?

https://github.com/YarusskiDev/ProjetoLaravel/blob/ac2209a9eb6863346a7f9d247b8be92a53a2f303/projetoCinema/app/Actions/Fortify/CreateNewUser.php#L1-L36

**Comment by YarusskiDev** [comment]
não entendi, achei que credencias seria isso?

**Comment by rafamancan** [comment]
Mas não tinha requisito para criar a tela de cadastro de usuário, apenas que precisaria fornecer as credenciais
