### ISSUE TITLE
Indentação e fora de padrão (pt-br VS en-us)

### ISSUE THREAD

**Issue by rafamancan** [YarusskiDev/ProjetoLaravel#3]
Muitos espaços sobrando
Nomenclatura sem seguir um padrão

https://github.com/YarusskiDev/ProjetoLaravel/blob/ac2209a9eb6863346a7f9d247b8be92a53a2f303/projetoCinema/app/Http/Controllers/FilmeController.php#L1-L97

**Comment by YarusskiDev** [comment]
fixed
