### ISSUE TITLE
Isso tá me dando muita dor

### ISSUE THREAD

**Issue by rafamancan** [YarusskiDev/ProjetoLaravel#4]
As variaveis e nomes de funções em português, a mensagem que retorna pro usuário tá em Inglês :(
https://github.com/YarusskiDev/ProjetoLaravel/blob/ac2209a9eb6863346a7f9d247b8be92a53a2f303/projetoCinema/app/Http/Controllers/UsuarioLoginController.php#L37-L41

**Comment by YarusskiDev** [comment]
fixed
